apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: size
  template:
    metadata:
      labels:
        app: size
    spec:
      containers:
      - name: size
        image: mhausenblas/simpleservice:0.5.0
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVIC_VERSION
          value: "0.9"
