apiVersion: v1
kind: Pod
metadata:
  name: constraintpod
spec:
 containers:
 - name: size
   image: mhausenblas/simpleservice:0.5.0
   ports:
   - containerPort: 9877
   resources:
     limits:
       memory: "64Mi"
       cpu: "500m"
