apiVersion: v1
kind: ReplicationController
metadata:
  name: rcapp
spec:
  replicas: 1
  selector:
    app: myapp
  template:
    metadata:
      name: applicationrc
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mhausenblas/simpleservice:0.5.0
        ports:
        - containerPort: 9876
